# Copy this file to config_local.py for local-only settings.
# Never commit config_local.py if it contains real credentials.

EMAIL_ENABLED = True
EMAIL_DELIVERY_METHOD = "GMAIL_API"  # GMAIL_API, SMTP, or BREVO
EMAIL_SENDER = "nilesh.shah1807@gmail.com"
EMAIL_RECEIVER = "nilesh.shah1807@gmail.com"
EMAIL_PASSWORD = "YOUR_GMAIL_APP_PASSWORD"
ATTACH_CSV = True
GMAIL_CLIENT_ID = "YOUR_GOOGLE_OAUTH_CLIENT_ID"
GMAIL_CLIENT_SECRET = "YOUR_GOOGLE_OAUTH_CLIENT_SECRET"
GMAIL_REFRESH_TOKEN = "YOUR_GOOGLE_OAUTH_REFRESH_TOKEN"
BREVO_API_KEY = "YOUR_BREVO_API_KEY"
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 465
SMTP_TIMEOUT_SECONDS = 30
SMTP_FORCE_IPV4 = True


OUTPUT_DIR = "reports_advanced"
YFINANCE_CACHE_DIR = "reports_advanced/yfinance_cache"
FUND_CACHE_MAX_AGE_DAYS = 7
PRICE_CACHE_MAX_AGE_HOURS = 18

# Financial Services and Real Estate have built-in sector models. Add a sector
# here only when it should be capped until another dedicated model is written.
SPECIALIZED_FUNDAMENTAL_SECTORS = ["Financial Services", "Real Estate"]
REQUIRE_UPTREND_FOR_BUY = True
BUY_MIN_MA50_SLOPE = 0.0
BUY_MIN_3M_RETURN = 0.0

SCAN_ALL_NSE = False
CUSTOM_WATCHLIST = ["RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK"]

REVERSE_DCF_ENABLED = True
REVERSE_DCF_FORECAST_YEARS = 5
REVERSE_DCF_DISCOUNT_RATE = 0.11
REVERSE_DCF_TERMINAL_GROWTH = 0.04
REVERSE_DCF_BASE_GROWTH = 0.15
REVERSE_DCF_RANKING_WEIGHT = 0.10

# Treat transcript sentiment as a research feature until backtests support more weight.
TRANSCRIPT_SENTIMENT_ENABLED = True
TRANSCRIPT_SENTIMENT_WEIGHT = 0.05
REQUIRE_TRANSCRIPT_FOR_STRONG_BUY = True
TRANSCRIPT_MIN_TECHNICAL_SCORE = 45.0
TRANSCRIPT_FULL_WEIGHT_TECHNICAL_SCORE = 60.0
TRANSCRIPT_MIN_PRIORITY_SCORE = 55.0
TRANSCRIPT_MAX_PRIORITY_RISK = 60.0
TRANSCRIPT_FAIL_ON_ERROR = True
SUPABASE_URL = "https://YOUR_PROJECT.supabase.co"
SUPABASE_SERVICE_ROLE_KEY = "YOUR_SUPABASE_SERVICE_ROLE_KEY"
SUPABASE_TIMEOUT_SECONDS = 30

TRANSCRIPT_LOOKBACK_DAYS = 120
TRANSCRIPT_OCR_ENABLED = True
TRANSCRIPT_MAX_DOCUMENTS_PER_RUN = 60
TRANSCRIPT_MAX_ANALYSES_PER_RUN = 60
