services:
  - type: cron
    name: ai-stock-screener
    runtime: python
    region: singapore
    schedule: "30 3 * * *"
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: EMAIL_ENABLED
        value: "True"
      - key: EMAIL_DELIVERY_METHOD
        value: GMAIL_API
      - key: EMAIL_SENDER
        sync: false
      - key: EMAIL_RECEIVER
        sync: false
      - key: GMAIL_CLIENT_ID
        sync: false
      - key: GMAIL_CLIENT_SECRET
        sync: false
      - key: GMAIL_REFRESH_TOKEN
        sync: false
      - key: ATTACH_CSV
        value: "True"
      - key: ATTACH_PDF
        value: "True"